### ISSUE TITLE
Agiografie, serendipità e plagi

### ISSUE THREAD

**Issue by valerio-bozzolan** [LegolasTheElf/mannaggia#20]
Lascio qui da marcare come `invalid` `wontfix` per i posteri.

Ho letto il termine *agiografare* su it.wiki e non sapendo che provenisse dall'*[agiografia](https://it.wikipedia.org/wiki/Agiografia)* me lo stavo cercando su DuckDuckGo.

Bene. Sorprendentemente, fra tutte le potenziali tematiche indicizzabili, il primo risultato di DuckDuckGo cercando *agiografare* è [un arcaico mannaggiatore](https://arekfu.blogspot.it/2009/02/elogio-della-bestemmia.html)...  risalente al 2009!

La serendipità ha colpito abbastanza, vado a dormire per oggi.

**Comment by YellowPecora** [comment]
una issue degna di essere aperta

**Comment by LegolasTheElf** [comment]
WOW. sempre più remota :-D
